// Datos de prueba que replican la forma exacta que devuelve Supabase REST API

export const DEALER_FIXTURE = {
  id: 1,
  name: "AutoTest Buenos Aires",
  plan_code: "pro",
  plan_status: "active",
  logo_url: null,
  image_url: null,
  contact_phone: "1155550001",
  phone_whatsapp: "5491155550001",
  province: "Buenos Aires",
  city: "Buenos Aires",
  extra_publish_slots: 0,
  publications_used: 1,
  plan_expires_at: "2027-01-01T00:00:00Z",
  can_receive_sell_vehicle_leads: true,
};

export const VEHICLE_FIXTURE = {
  id: "test-vehicle-001",
  created_at: "2026-01-15T10:00:00Z",
  brand: "Toyota",
  model: "Corolla",
  version: "XEI 2.0",
  year: 2022,
  price: 8500000,
  currency: "ARS",
  km: 35000,
  body_type: "sedan",
  transmission: "Automática",
  fuel_type: "Nafta",
  dealer_id: 1,
  dealer_name: "AutoTest Buenos Aires",
  dealer_phone: "1155550001",
  location: "Buenos Aires, Buenos Aires",
  province: "Buenos Aires",
  city: "Buenos Aires",
  main_image_url: null,
  image_url: null,
  images_json: [],
  status: "active",
  publication_status: "active",
  financing: false,
  featured: false,
  description: "Toyota Corolla en excelente estado, único dueño.",
  details: null,
  avg: null,
  market_reference_price: null,
  usage: null,
  views: 120,
  leads_count: 3,
  contraoferta_habilitada: false,
  doors: 4,
  reserved: false,
  reserved_by: null,
  delivery: false,
  months: null,
  rate: null,
  is_active: true,
  review_status: "approved",
  maintenance_info: null,
  show_maintenance_info: false,
  dealers: [DEALER_FIXTURE],
};

export const VEHICLE_RESERVED_FIXTURE = {
  ...VEHICLE_FIXTURE,
  id: "test-vehicle-002",
  brand: "Ford",
  model: "Focus",
  version: "SE 1.6",
  year: 2020,
  price: 5200000,
  km: 58000,
  reserved: true,
  publication_status: "reserved",
};

export const DEALER_PUBLIC_FIXTURE = {
  ...DEALER_FIXTURE,
  commercial_name: "AutoTest Buenos Aires",
  profile_id: "uuid-test-profile",
  rank: "pro",
  verified: true,
};
